const fs = require('fs');
const text = `1st1
main_hero.data.head
Masha
0.11%56.42%0.65%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
2nd2
main_hero.data.head
Gloo
0.57%55.47%70.16%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
3rd3
main_hero.data.head
Gord
1.41%55.46%2.21%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
4
main_hero.data.head
Lolita
0.12%55.17%1.49%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
5
main_hero.data.head
Marcel
0.25%54.69%81.96%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
6
main_hero.data.head
Hanabi
3.38%54.50%11.71%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
7
main_hero.data.head
Sun
1.64%54.11%35.47%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
8
main_hero.data.head
Diggie
0.20%53.91%12.04%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
9
main_hero.data.head
Kaja
0.29%53.71%8.65%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
10
main_hero.data.head
Khufra
0.26%53.38%2.82%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
11
main_hero.data.head
Floryn
1.04%53.21%34.38%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
12
main_hero.data.head
Leomord
1.09%53.10%11.41%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
13
main_hero.data.head
Belerick
1.45%52.97%8.17%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
14
main_hero.data.head
Valir
1.04%52.97%2.51%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
15
main_hero.data.head
Silvanna
1.30%52.89%3.04%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
16
main_hero.data.head
Popol and Kupa
0.28%52.87%0.33%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
17
main_hero.data.head
Minotaur
0.46%52.83%7.12%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
18
main_hero.data.head
Khaleed
0.37%52.82%0.77%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
19
main_hero.data.head
Terizla
0.68%52.80%0.93%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
20
main_hero.data.head
Hilda
1.04%52.62%20.47%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
21
main_hero.data.head
Argus
0.41%52.60%1.36%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
22
main_hero.data.head
Estes
0.66%52.42%51.42%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
23
main_hero.data.head
Benedetta
0.45%52.22%0.82%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
24
main_hero.data.head
Minsitthar
0.88%51.91%23.26%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
25
main_hero.data.head
Zhask
0.34%51.73%0.42%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
26
main_hero.data.head
Irithel
0.46%51.70%0.30%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
27
main_hero.data.head
Uranus
0.49%51.70%0.92%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
28
main_hero.data.head
Miya
2.74%51.68%5.12%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
29
main_hero.data.head
Melissa
0.65%51.67%1.16%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
30
main_hero.data.head
Atlas
0.46%51.64%5.39%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
31
main_hero.data.head
Zetian
2.03%51.61%25.27%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
32
main_hero.data.head
Rafaela
0.33%51.56%2.67%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
33
main_hero.data.head
Yve
0.10%51.48%0.14%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
34
main_hero.data.head
Freya
1.15%51.48%20.44%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
35
main_hero.data.head
Kadita
0.99%51.46%8.06%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
36
main_hero.data.head
Aamon
0.80%51.38%8.02%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
37
main_hero.data.head
Paquito
0.92%51.37%2.05%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
38
main_hero.data.head
Bane
0.32%51.33%0.23%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
39
main_hero.data.head
Fredrinn
0.70%51.32%6.49%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
40
main_hero.data.head
Carmilla
0.54%51.30%1.48%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
41
main_hero.data.head
Cyclops
0.79%51.28%0.42%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
42
main_hero.data.head
Suyou
2.01%51.28%31.12%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
43
main_hero.data.head
Edith
0.20%51.24%0.10%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
44
main_hero.data.head
Phoveus
0.66%51.15%2.66%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
45
main_hero.data.head
Aulus
0.30%50.96%2.94%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
46
main_hero.data.head
Hanzo
0.32%50.96%2.88%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
47
main_hero.data.head
Zhuxin
0.52%50.90%28.01%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
48
main_hero.data.head
Clint
0.82%50.87%0.88%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
49
main_hero.data.head
Baxia
0.16%50.86%0.30%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
50
main_hero.data.head
Ruby
0.46%50.86%0.51%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
51
main_hero.data.head
Vale
0.63%50.82%0.37%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
52
main_hero.data.head
Odette
0.73%50.80%0.59%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
53
main_hero.data.head
Guinevere
1.25%50.78%33.00%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
54
main_hero.data.head
Vexana
1.93%50.77%1.69%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
55
main_hero.data.head
Akai
0.53%50.69%2.52%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
56
main_hero.data.head
Brody
0.48%50.66%0.53%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
57
main_hero.data.head
Natan
0.37%50.66%0.28%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
58
main_hero.data.head
Natalia
0.29%50.57%2.12%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
59
main_hero.data.head
Badang
0.91%50.45%1.12%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
60
main_hero.data.head
Johnson
0.85%50.43%2.70%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
61
main_hero.data.head
Beatrix
0.73%50.20%0.72%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
62
main_hero.data.head
Thamuz
1.13%50.14%4.44%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
63
main_hero.data.head
Obsidia
0.86%50.13%2.29%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
64
main_hero.data.head
Kagura
0.63%50.12%1.64%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
65
main_hero.data.head
Moskov
0.96%50.08%0.36%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
66
main_hero.data.head
Aldous
0.35%50.07%0.48%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
67
main_hero.data.head
Ixia
0.85%50.03%1.77%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
68
main_hero.data.head
Julian
1.25%50.03%4.12%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
69
main_hero.data.head
Karrie
0.89%50.01%3.77%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
70
main_hero.data.head
Alice
0.79%50.01%10.42%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
71
main_hero.data.head
Yi Sun-shin
1.48%49.97%12.97%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
72
main_hero.data.head
Lukas
0.34%49.96%0.75%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
73
main_hero.data.head
Harley
1.19%49.90%71.31%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
74
main_hero.data.head
Helcurt
0.84%49.88%29.56%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
75
main_hero.data.head
Alucard
0.59%49.85%0.72%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
76
main_hero.data.head
Saber
1.00%49.82%22.74%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
77
main_hero.data.head
Barats
0.13%49.60%0.10%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
78
main_hero.data.head
Claude
0.95%49.55%0.53%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
79
main_hero.data.head
X.Borg
0.65%49.51%4.25%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
80
main_hero.data.head
Faramis
0.10%49.39%0.82%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
81
main_hero.data.head
Gusion
1.66%49.36%12.42%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
82
main_hero.data.head
Roger
0.31%49.32%0.11%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
83
main_hero.data.head
Cecilion
0.64%49.28%0.23%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
84
main_hero.data.head
Chang'e
0.83%49.04%0.61%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
85
main_hero.data.head
Eudora
0.81%49.02%2.48%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
86
main_hero.data.head
Harith
0.63%48.95%3.66%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
87
main_hero.data.head
Angela
1.61%48.88%7.48%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
88
main_hero.data.head
Lylia
0.66%48.85%1.94%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
89
main_hero.data.head
Lapu-Lapu
0.54%48.71%1.01%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
90
main_hero.data.head
Joy
0.23%48.66%1.10%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
91
main_hero.data.head
Chip
0.06%48.65%3.09%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
92
main_hero.data.head
Hylos
0.37%48.53%1.22%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
93
main_hero.data.head
Sora
0.82%48.50%44.87%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
94
main_hero.data.head
Hayabusa
0.89%48.41%5.09%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
95
main_hero.data.head
Lunox
0.30%48.38%0.50%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
96
main_hero.data.head
Wanwan
0.18%48.33%0.32%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
97
main_hero.data.head
Dyrroth
1.30%48.30%1.18%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
98
main_hero.data.head
Layla
1.10%48.21%1.09%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
99
main_hero.data.head
Yin
0.57%48.20%3.12%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
100
main_hero.data.head
Nana
1.64%48.15%4.78%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
101
main_hero.data.head
Jawhead
0.43%48.14%0.39%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
102
main_hero.data.head
Arlott
0.46%47.90%0.63%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
103
main_hero.data.head
Grock
0.64%47.90%5.87%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
104
main_hero.data.head
Cici
0.36%47.86%1.56%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
105
main_hero.data.head
Bruno
0.23%47.84%0.15%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
106
main_hero.data.head
Xavier
0.50%47.82%0.32%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
107
main_hero.data.head
Selena
1.25%47.77%3.25%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
108
main_hero.data.head
Yu Zhong
1.33%47.76%2.83%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
109
main_hero.data.head
Kimmy
0.70%47.56%0.67%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
110
main_hero.data.head
Tigreal
2.00%47.54%7.06%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
111
main_hero.data.head
Nolan
0.27%47.52%0.75%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
112
main_hero.data.head
Aurora
0.40%47.50%0.27%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
113
main_hero.data.head
Novaria
0.77%47.50%1.17%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
114
main_hero.data.head
Zilong
0.94%47.30%0.71%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
115
main_hero.data.head
Pharsa
0.71%47.27%0.48%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
116
main_hero.data.head
Alpha
1.13%47.13%0.75%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
117
main_hero.data.head
Gatotkaca
0.73%47.10%0.54%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
118
main_hero.data.head
Luo Yi
0.17%46.95%0.10%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
119
main_hero.data.head
Chou
1.08%46.70%3.26%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
120
main_hero.data.head
Martis
0.60%46.59%0.65%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
121
main_hero.data.head
Lesley
1.85%46.55%8.25%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
122
main_hero.data.head
Karina
0.55%46.37%2.11%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
123
main_hero.data.head
Kalea
0.35%46.21%2.81%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
124
main_hero.data.head
Ling
0.19%45.60%0.17%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
125
main_hero.data.head
Franco
1.28%44.50%6.82%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
126
main_hero.data.head
Lancelot
0.66%43.39%1.06%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
127
main_hero.data.head
Valentina
0.18%43.38%0.42%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
128
main_hero.data.head
Balmond
0.29%43.34%0.25%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
129
main_hero.data.head
Esmeralda
0.38%43.33%0.65%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
130
main_hero.data.head
Mathilda
0.10%43.31%0.57%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
131
main_hero.data.head
Fanny
0.61%42.81%3.18%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
132
main_hero.data.head
Granger
1.45%42.51%3.22%
hero.data.head
hero.data.head
hero.data.head
hero.data.head
hero.data.head
`;

let lines = text.split('\n');
let data = {
  lastUpdated: new Date().toISOString(),
  source: "Official MLBB Rank - " + new Date().toLocaleDateString(),
  heroes: {}
};

for (let i = 0; i < lines.length; i++) {
  if (lines[i] === 'main_hero.data.head') {
    let heroNameRaw = lines[i+1].trim();
    let statsRaw = lines[i+2].trim();
    
    // Parse stats string like "0.11%56.42%0.65%"
    const matches = statsRaw.match(/([0-9.]+)%([0-9.]+)%([0-9.]+)%/);
    if (matches && heroNameRaw) {
      let pick = parseFloat(matches[1]);
      let win = parseFloat(matches[2]);
      let ban = parseFloat(matches[3]);
      
      let id = heroNameRaw.toLowerCase().replace(/[^a-z]/g, '');
      
      // Some specific id corrections if needed
      if(id === 'yisunshin') id = 'yisunshin';
      if(id === 'lapulapu') id = 'lapulapu';
      if(id === 'yuzhong') id = 'yuzhong';
      if(id === 'xborg') id = 'xborg';
      if(id === 'popolandkupa') id = 'popol';
      if(id === 'luoyi') id = 'luo_yi';
      if(id === 'change') id = 'change';
      
      data.heroes[id] = { winRate: win, pickRate: pick, banRate: ban };
    }
  }
}

data.heroCount = Object.keys(data.heroes).length;
fs.writeFileSync('src/data/liveMeta.json', JSON.stringify(data, null, 2));
console.log("File liveMeta.json aggiornato con successo! Eroi estratti: " + data.heroCount);
