export const getTagColor = (tag: string) => {
  const t = tag.toLowerCase();
  if (t.includes('cc') || t.includes('stun') || t.includes('control') || t.includes('freeze') || t.includes('slow') || t.includes('suppress') || t.includes('knock')) 
    return 'bg-sky-500/10 text-sky-400 border-sky-500/20';
  if (t.includes('burst') || t.includes('damage') || t.includes('shred') || t.includes('penetration') || t.includes('execute') || t.includes('crit')) 
    return 'bg-rose-500/10 text-rose-400 border-rose-500/20';
  if (t.includes('sustain') || t.includes('heal') || t.includes('regen') || t.includes('lifesteal') || t.includes('shield') || t.includes('immortality')) 
    return 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20';
  if (t.includes('mobility') || t.includes('dash') || t.includes('teleport') || t.includes('speed') || t.includes('chase') || t.includes('blink')) 
    return 'bg-purple-500/10 text-purple-400 border-purple-500/20';
  if (t.includes('tank') || t.includes('pv') || t.includes('defense') || t.includes('armor') || t.includes('heavy') || t.includes('size')) 
    return 'bg-amber-500/10 text-amber-400 border-amber-500/20';
  if (t.includes('poke') || t.includes('range') || t.includes('continuous')) 
    return 'bg-blue-500/10 text-blue-400 border-blue-500/20';
  return 'bg-slate-800/50 text-slate-400 border-slate-700/50';
}

export const translateTag = (tag: string) => {
  const map: Record<string, string> = {
    'highCC': 'Alto CC',
    'knockback': 'Respinta',
    'shieldPV': 'Scudo PV',
    'lateGameBurst': 'Burst Fine Gioco',
    'stackDamage': 'Danno Cumulativo',
    'chase': 'Inseguimento',
    'aoeSustain': 'Sostenibilità AoE',
    'teleport': 'Teletrasporto',
    'highPVMagic': 'Tank Magico',
    'trueDamage': 'Danno Puro',
    'sustainSpam': 'Sustain Continuo',
    'slow': 'Rallentamento',
    'lifestealDPS': 'Rubavita DPS',
    'groupCC': 'CC di Gruppo',
    'aoeStun': 'Stun AoE',
    'freezeCC': 'Congelamento',
    'burstMagico': 'Burst Magico',
    'aoeControl': 'Controllo AoE',
    'wallCreate': 'Crea Muri',
    'burstStun': 'Burst Stun',
    'shieldImmunity': 'Scudo Immunità',
    'executeUltimate': 'Esecuzione Ulti',
    'jungleSustain': 'Sustain Giungla',
    'pokeAoE': 'Poke AoE',
    'heal': 'Cura',
    'pushTurret': 'Spinta Torri',
    'highPVPhysical': 'Tank Fisico',
    'suppressCC': 'Soppressione',
    'stackSize': 'Dimensione Cumulo',
    'builtInAntiHeal': 'Anti-Cura Integrato',
    'highMobilityRoam': 'Alta Mobilità',
    'tauntCC': 'Provocazione',
    'passiveReflect': 'Riflesso Passiva',
    'counterDPS': 'Contrasta DPS',
    'dashSpam': 'Spam Scatti',
    'immunityCC': 'Immunità CC',
    'burstFisico': 'Burst Fisico',
    'markStack': 'Cumulo Marchio',
    'highCritDPS': 'DPS Critico Alto',
    'rangePoke': 'Poke a Distanza',
    'damageShare': 'Danno Condiviso',
    'ccAoE': 'CC AoE',
    'stealDefense': 'Ruba Difesa',
    'infiniteManaStack': 'Mana Infinito',
    'continuousMagic': 'Magia Continua',
    'shieldActive': 'Scudo Attivo',
    'fastPush': 'Push Rapido',
    'suppressSingle': 'Soppressione Singola',
    'immunityDash': 'Scatto Immunità',
    'attackSpeedDPS': 'DPS Velocità Attacco',
    'highMobility': 'Alta Mobilità',
    'aoeUltimate': 'Ulti AoE',
    'burstPassive': 'Burst Passiva',
    'singleLockCC': 'Blocco Singolo',
    'spamAbilita': 'Spam Abilità',
    'sustainMagico': 'Sustain Magico',
    'antiCCGlobal': 'Anti-CC Globale',
    'shieldAoE': 'Scudo AoE',
    'slowBombs': 'Bombe Rallentanti',
    'shredDefense': 'Riduzione Difesa',
    'earlyGameBurst': 'Burst Inizio Gioco',
    'lifesteal': 'Rubavita',
    'shieldAbsorb': 'Assorbimento Scudo',
    'sustainContinuous': 'Sustain Continuo',
    'aoeHealSpam': 'Cura AoE',
    'teamSustain': 'Sostenibilità Team',
    'singleTargetBurst': 'Burst Singolo',
    'instantStun': 'Stun Istantaneo',
    'extremeMobility': 'Estra-Mobilità',
    'energySpam': 'Spam Energia',
    'wallDash': 'Scatto su Muro',
    'resurrectionAoE': 'Resurrezione AoE',
    'pullCC': 'Trazione CC',
    'burstMagicGroup': 'Burst Magico Gruppo',
    'globalHeal': 'Cura Globale',
    'antiAntiHeal': 'Anti Anti-Cura',
    'stun': 'Stordimento',
    'hookSingle': 'Gancio Singolo',
    'fastPick': 'Pick Rapido',
    'tauntDamageReflect': 'Riflesso Danno',
    'shieldSpam': 'Spam Scudo',
    'highAttackSpeed': 'Alta Vel. Attacco',
    'passiveArmorReflect': 'Corazza Passiva',
    'attachToEnemy': 'Attacca a Nemico',
    'slowSpam': 'Spam Rallento',
    'regenPV': 'Rigenerazione PV',
    'trueDamageContinuous': 'Danno Puro Continuo',
    'aoeMelt': 'Fusione AoE',
    'mobilityDash': 'Scatto Mobilità',
    'jungleFast': 'Giungla Rapida',
    'heavyTank': 'Tank Pesante',
    'immunitàCC': 'Immunità CC',
    'dannoFisicoIniziale': 'Danno Fisico Iniziale',
    'knockupCC': 'Lancio in Aria',
    'jumpDash': 'Salto/Scatto',
    'instantBurstMagic': 'Burst Magico Rapido',
    'dashRecall': 'Ritorno con Scatto',
    'bounceAttack': 'Attacco Rimbalzo',
    'ccImmunityShield': 'Scudo Immunità CC',
    'aoeImmobilize': 'Immobilizza AoE',
    'hitAndRun': 'Colpisci e Fuggi',
    'cardMark': 'Marchio Carte',
    'shadowTeleport': 'Teletrasporto Ombra',
    'invincibleUltimate': 'Ulti Invincibile',
    'blindMap': 'Mappa Oscurata',
    'silenceCC': 'Silenziamento',
    'instantBurstFisico': 'Burst Fisico Rapido',
    'manaToPV': 'Mana in PV',
    'continuousAoeSlow': 'Rallento AoE',
    'teamSpeedPath': 'Sentiero Velocità',
    'shootWhileMoving': 'Spara in Movimento',
    'aoeCritDPS': 'DPS Critico AoE',
    'armorShred': 'Riduzione Armatura',
    'aoeUltimateRange': 'Raggio Ulti AoE',
    'sustainPassive': 'Sustain Passivo',
    'throwEjectCC': 'Lancio/Espulsione',
    'globalCarDrive': 'Guida Globale',
    'aoeStunCrash': 'Scontro AoE Stun',
    'shieldLowPV': 'Scudo Bassi PV',
    'dashRhythm': 'Ritmo Scatti',
    'ccImmunity': 'Immunità CC',
    'aoeMagicBurst': 'Burst Magico AoE',
    'enhancedAbilita': 'Abilità Potenziate',
    'knockupOrImmunity': 'Lancio o Immunità',
    'lifestealMagic': 'Rubavita Magico',
    'passiveHeal': 'Cura Passiva',
    'umbrellaTeleport': 'Teletrasporto Ombrello',
    'ccPurifyBuiltIn': 'Purifica Integrato',
    'aoeBurstControl': 'Burst Controllo AoE',
    'pullEnemy': 'Trazione Nemico',
    'damageReduction': 'Riduzione Danno',
    'trueDamagePassive': 'Danno Puro Passivo',
    'basicAttackBlock': 'Blocco Attacco Base',
    'resetUltimate': 'Reset Ulti',
    'trueDamagePercent': 'Danno Puro %',
    'tankMelter': 'Sciogli Tank',
    'fastHealChannel': 'Cura Canalizzata',
    'aoeStunUltimate': 'Stun Ulti AoE',
    'antiDashBall': 'Sfera Anti-Scatto',
    'jumpStun': 'Salto con Stun',
    'wallPinCC': 'Inchioda a Muro',
    'continuousMagicMove': 'Movimento Magico',
    'aimJoystick': 'Mira Joystick',
    'invincibilityAbilita': 'Invincibilità',
    'ccImmunityHeavy': 'Immunità CC Pesante',
    'aoeBurstFisico': 'Burst Fisico AoE',
    'extremeRange': 'Gittata Estrema',
    'lateGameCritDPS': 'Critici Late Game',
    'mountedEnhanced': 'Potenziato a Cavallo',
    'guaranteedCritLowPV': 'Critico Garantito',
    'pushCC': 'Spinta CC',
    'trueDamageSniper': 'Cecchino Danno Puro',
    'camouflageMobility': 'Mimica e Mobilità',
    'wallWalk': 'Cammina su Muri',
    'shieldReflectProjectiles': 'Riflette Proiettili',
    'aoeStunCharge': 'Carica Stun AoE',
    'magicPenetrationPercent': 'Penetrazione Magica %',
    'invincibilityBrilliance': 'Invincibilità Splendente',
    'controlloAoE': 'Controllo AoE',
    'altaMobilitaTeam': 'Mobilità Team Alta',
    'aoeGloomSpam': 'Spam Oscurità AoE',
    'timeRecallHeal': 'Ritorno Temporale',
    'slowContinuous': 'Rallento Continuo',
    'ccImmunityActive': 'Immunità CC Attiva',
    'damageReductionDash': 'Riduzione Danno Scatto',
    'trueDamageExecute': 'Esecuzione Danno Puro',
    'threeHPBars': '3 Barre di Vita',
    'extremeAttackSpeed': 'Vel. Attacco Estrema',
    'disarmCC': 'Disarmo CC',
    'wispTeamDash': 'Scatto Team Fuoco Fatuo',
    'antiMeleeBubble': 'Bolla Anti-Mischia',
    'dollLinkDamage': 'Danno Collegato Bambola',
    'tripleKnockupAoE': 'Triplo Lancio AoE',
    'aoeHeal': 'Cura AoE',
    'rageDefense': 'Difesa dalla Rabbia',
    'invisiblePurifyUltimate': 'Invisibilità e Purifica',
    'multiTargetCrit': 'Critici Multi-Target',
    'molinaTransformCC': 'Trasformazione Molina',
    'passiveMolinaEscape': 'Fuga Molina Passiva',
    'aoeBurstMagic': 'Burst Magico AoE',
    'stealthInvisibility': 'Invisibilità Furtiva',
    'silenceSmoke': 'Fumo Silenziante',
    'immuneBasicAttacks': 'Immune Attacchi Base',
    'magicAttackSpeedDPS': 'DPS Magico Rapido',
    'cloneDamage': 'Danno Cloni',
    'riftExplosionBurst': 'Burst Esplosione Rift',
    'builtInPurify': 'Purifica Integrato',
    'longRangeSniper': 'Cecchino Lungo Raggio',
    'revealMap': 'Rivela Mappa',
    'slowPercent': 'Rallentamento %',
    'massiveAoeUltimate': 'Massiccia Ulti AoE',
    'shieldChanneling': 'Scudo Canalizzato',
    'bounceCC': 'CC a Rimbalzo',
    'comboSpamNoCooldown': 'Spam Combo No CD',
    'artilleryAoeUltimate': 'Artiglieria AoE',
    'birdEscape': 'Fuga in Forma Uccello',
    'stunMark': 'Marchio con Stun',
    'antiDashCounter': 'Contrasta Scatti',
    'aoeJump': 'Salto AoE',
    'wolfCompanion': 'Compagno Lupo',
    'trapCC': 'Trappola CC',
    'singleTargetStun': 'Stun Singolo',
    'healSpeedAoE': 'Cura e Vel. AoE',
    'slowPoke': 'Poke Rallentante',
    'lineStun': 'Stun in Linea',
    'wolfFormExecute': 'Forma Lupo Esecuzione',
    'humanFormPoke': 'Forma Umana Poke',
    'aoeStunPull': 'Stun e Trazione AoE',
    'extremeSpellVamp': 'Spell Vamp Estremo',
    'defensePassiveDash': 'Difesa Scatto Passiva',
    'knockupSingleBurst': 'Burst Lancio Singolo',
    'longStunArrow': 'Freccia Stun Lunga',
    'trapVision': 'Visione Trappole',
    'abyssalBurst': 'Burst Abissale',
    'cloneSpam': 'Spam Cloni',
    'dpsTankMelter': 'DPS Sciogli Tank',
    'damageReductionPV': 'Riduzione Danno PV',
    'heavyAoeStun': 'Stun Pesante AoE',
    'slowHammer': 'Martello Rallentante',
    'scytheTrueDamage': 'Falce Danno Puro',
    'ultimateRegenPV': 'Regen PV con Ulti',
    'aoePushPull': 'Spinta/Trazione AoE',
    'stunUltimate': 'Stun con Ulti',
    'antiBasicAttack': 'Anti-Attacco Base',
    'aoeKnockup': 'Lancio in Aria AoE',
    'vacuumUltimateBurst': 'Ulti Sottovuoto',
    'copyUltimateEnemy': 'Copia Ulti Nemica',
    'lifestealPassive': 'Rubavita Passivo',
    'knockbackAntiMelee': 'Respinta Anti-Mischia',
    'continuousBurnStun': 'Bruciatura e Stun',
    'purifyUltimate': 'Purifica con Ulti',
    'knightSummon': 'Evoca Cavaliere',
    'aoeTerrifyCC': 'Terrore AoE',
    'firagaArmorShield': 'Corazza Firaga',
    'trueDamageBurn': 'Bruciatura Danno Puro',
    'globalUltimate': 'Ulti Globale',
    'ccImmobilizeWall': 'Muro Immobilizzante',
    'enhancedSpam': 'Spam Potenziato',
    'weaponSwitchPassive': 'Cambio Armi Passivo',
    'globalRevealMap': 'Rivela Mappa Globale',
    'ccImmunityDash': 'Scatto Immunità CC',
    'arena1v1Isolation': 'Isolamento Arena 1v1',
    'burstStunTransform': 'Trasforma Burst Stun',
    'dragonFormGlobal': 'Forma Dragone Globale',
    'shaEssenceSustain': 'Sustain Essenza Sha',
    'gridAoeSlow': 'Rallentamento Griglia',
    'ccImmunityShieldUltimate': 'Scudo Immunità CC',
    'spawnSpawn': 'Evoca Progenie',
    'ultimateMergeInvincibility': 'Fusione Invincibile',
    'lanternAoePull': 'Trazione Lanterna AoE',
    'airborneCC Continuous': 'Lancio Aria Continuo',
    'manaSustain': 'Sustain Mana',
    'slowImmunity': 'Immunità Rallento',
    'flipBackCC': 'Lancio all\'Indietro',
    'camouflage': 'Mimetizzazione',
    'daggers': 'Pugnali',
    'lateGameDPS': 'DPS Late Game',
    'autoAttack': 'Attacco Base',
    'aoeSlow': 'Rallento AoE',
    'dashTarget': 'Scatto su Bersaglio',
    'crowdControl': 'Controllo Folla',
    'multiWeapon': 'Multi-Arma',
    'highBurst': 'Alto Burst',
    'mobilityDPS': 'DPS Mobilità',
    'yoYo': 'Yo-Yo',
    'singleTarget': 'Bersaglio Singolo',
    'portalGlobal': 'Portale Globale',
    'transformation': 'Trasformazione',
    'tankDpsMagic': 'Tank DPS Magico',
    'jungleSteal': 'Furto Giungla',
    'shadowForm': 'Forma Ombra',
    'antiDash': 'Anti-Scatto',
    'hookPull': 'Trazione con Gancio',
    'shieldBash': 'Colpo di Scudo',
    'lockSingleTarget': 'Blocca Bersaglio',
    'transformationForms': 'Forme Trasformazione',
    'charge': 'Carica',
    'dashJump': 'Salto/Scatto',
    'weaknessMark': 'Marchio Debolezza',
    'combo': 'Furia di Combo',
    'bushRegen': 'Regen in Erba',
    'dashAttack': 'Attacco con Scatto',
    'noStun': 'Nessuno Stun',
  };
  return map[tag] || tag;
}